[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"

[workspace.dependencies]
busman-core = { path = "crates/busman-core" }
bytes = "1"
byteorder = "1"
regex = "1"
num-traits = "0.2.19"
libc = "0.2"
log = "0.4.29"
env_logger = "0.11.10"
